# Generated by Django 3.2.6 on 2021-08-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
    ]
